---
- name: Install packages
  apt:
    name:
      - ntpdate
    state: present

- name: Create sync time cronjob
  cron:
    name: "Sync time"
    hour: "*/6"
    job: "/usr/sbin/ntpdate -u 'time.nist.gov' > /dev/null 2>&1 &"

- name: Sync time
  shell: "/usr/sbin/ntpdate -u 'time.nist.gov'"
