---
- name: Create Samba credentials file
  loop: "{{ samba_credentials }}"
  ansible.builtin.file:
    path: "{{ item.file }}"
    state: touch
    owner: root
    group: root
    mode: '0600'

- name: Add Samba credentials to file
  loop: "{{ samba_credentials }}"
  ansible.builtin.copy:
    dest: "{{ item.file }}"
    content: |
      username={{ item.username }}
      password={{ item.password }}
      domain={{ item.domain }}
    owner: root
    group: root
    mode: '0600'
