---
- name: Ensure mount point exists
  loop: "{{ samba_shares }}"
  ansible.builtin.file:
    path: "{{ item.mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0777'

- name: Add Samba share entry to /etc/fstab
  loop: "{{ samba_shares }}"
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "//{{ item.server }}{{ item.share_path }} {{ item.mount_point }} cifs credentials=/etc/samba/{{ item.server }}.smbclient,rw,_netdev,iocharset=utf8 0 0"
    state: present
