# export PB_NAME="${ANSIBLE_PB_DIR}exchange_ssh_keys.yml" && rm -f "${PB_NAME}" && nano "${PB_NAME}"
# export ANSIBLE_HOST_KEY_CHECKING=False && ansible-playbook --ask-pass -vvvv "${PB_NAME}"
---
- hosts: all
  gather_facts: false
  tasks:
    - name: Create SSH key if it does not exist
      file:
        path: ~/.ssh
        state: directory
        mode: '700'

    - name: Create SSH key if it does not exist
      file:
        path: ~/.ssh/id_rsa.pub
        state: touch
        mode: '0644'

    - name: Fetch all public ssh keys
      shell: cat ~/.ssh/id_rsa.pub
      register: ssh_keys
      tags:
        - ssh

    - name: check keys
      debug: msg="{{ ssh_keys.stdout }}"
      tags:
        - ssh

    - name: deploy keys on all servers
      authorized_key: user="{{ lookup('env', 'ANSIBLE_USER_NAME')}}" key="{{ item[0] }}"
      delegate_to: "{{ item[1] }}"
      with_nested:
        - "{{ ssh_keys.stdout }}"
        - "{{ groups['all'] }}"
      tags:
        - ssh
