# export PB_NAME="${ANSIBLE_PB_DIR}hushlogin.yml" && rm -f "${PB_NAME}" && nano "${PB_NAME}"
# ansible-playbook --ask-pass -vvvv "${PB_NAME}"
---
- hosts: all
  tasks:
    - name: Hushlogin
      file:
        path: ~/.hushlogin
        state: touch
