# export PLAYBOOK_NAME="mount_samba_share.yml" && rm -f "${PLAYBOOK_NAME}" && nano "${PLAYBOOK_NAME}"
# ansible-playbook --extra-vars "@$HOME/.ansible/vault.yml" --ask-vault-pass -vvvv "${PLAYBOOK_NAME}"
---
- hosts: all
  become: true

  roles:
    - update_packages
    - install_packages
    - create_samba_credentials
    - add_samba_share_into_fstab
    - remount_fstab_mounts

  vars:
    packages:
      - avahi-daemon
      - cifs-utils
      - psmisc
      - samba
      - samba-common
      - smbclient
      - wsdd

    samba_share:
      server: "smb.example.com"
      share_path: "/shared"
      mount_point: "/mnt/shared"

    samba_credentials:
      file: "/etc/samba/{{ samba_share.server }}.smbclient"
      username: "your_username"
      password: "your_password"
      domain: "WORKGROUP"
