# export PB_NAME="${ANSIBLE_PB_DIR}prepare_environment_k8s.yml" && rm -f "${PB_NAME}" && nano "${PB_NAME}"
# ansible-playbook --ask-pass --ask-become-pass -vvvv "${PB_NAME}"
---
- hosts: kube_node
  become: true
  become_method: sudo
  tasks:

    - name: Remove packages
      apt:
        name:
          - containerd.io
          - docker-ce-cli
        state: absent
        purge: yes

    - name: Clean apt
      apt:
        autoremove : yes
        autoclean: yes

