# export PB_NAME="${ANSIBLE_PB_DIR}reboot_all.yml" && rm -f "${PB_NAME}" && nano "${PB_NAME}"
# ansible-playbook --ask-pass --ask-become-pass -vvvv "${PB_NAME}"
---
- hosts: all
  become: true
  become_method: sudo
  ignore_errors: yes
  roles:
    reboot
