- name: Update and upgrade apt packages
  become: true
  ignore_errors: true
  apt:
    update_cache: true
    upgrade: true
    autoremove: true

- name: Update and upgrade yum packages
  become: true
  ignore_errors: true
  yum:
    name: "*"
    state: latest
    update_cache: true
    autoremove: true
